DO $$
BEGIN
  CREATE TYPE role AS ENUM ('superadmin', 'admin');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE estado_user AS ENUM ('activo', 'inactivo');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

DO $$
BEGIN
  CREATE TYPE presente_estado AS ENUM ('presente_votando', 'presente_ausente');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

CREATE TABLE IF NOT EXISTS comisiones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL UNIQUE,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS users (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role role NOT NULL,
  comision_id INTEGER NULL,
  ultimo_login TIMESTAMP(3) NULL,
  estado estado_user NOT NULL DEFAULT 'activo',
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  deleted_at TIMESTAMP(3) NULL,
  CONSTRAINT users_comision_id_fkey FOREIGN KEY (comision_id) REFERENCES comisiones(id)
);

CREATE TABLE IF NOT EXISTS delegados (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(255) NOT NULL,
  designacion VARCHAR(255) NOT NULL,
  comision_id INTEGER NOT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT delegados_comision_id_fkey FOREIGN KEY (comision_id) REFERENCES comisiones(id)
);

CREATE TABLE IF NOT EXISTS calificaciones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  delegado_id INTEGER NOT NULL UNIQUE,
  oratoria INTEGER NULL,
  argumentacion INTEGER NULL,
  negociacion INTEGER NULL,
  liderazgo INTEGER NULL,
  redaccion INTEGER NULL,
  ponderada DOUBLE PRECISION NOT NULL DEFAULT 0,
  presente_estado presente_estado NULL,
  pasa_minume_xvii BOOLEAN NULL,
  mencion TEXT NULL,
  feedback TEXT NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT calificaciones_delegado_id_fkey FOREIGN KEY (delegado_id) REFERENCES delegados(id)
);

CREATE TABLE IF NOT EXISTS audits (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NULL,
  action VARCHAR(100) NOT NULL,
  entity_type VARCHAR(100) NOT NULL,
  entity_id INTEGER NULL,
  changes JSONB NULL,
  created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT audits_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS config (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key VARCHAR(255) NOT NULL UNIQUE,
  value TEXT NULL,
  updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS users_email_idx ON users(email);
CREATE INDEX IF NOT EXISTS users_role_idx ON users(role);
CREATE INDEX IF NOT EXISTS delegados_comision_id_idx ON delegados(comision_id);
CREATE INDEX IF NOT EXISTS delegados_nombre_idx ON delegados(nombre);
CREATE INDEX IF NOT EXISTS calificaciones_delegado_id_idx ON calificaciones(delegado_id);
CREATE INDEX IF NOT EXISTS calificaciones_ponderada_idx ON calificaciones(ponderada);
CREATE INDEX IF NOT EXISTS audits_user_id_idx ON audits(user_id);
CREATE INDEX IF NOT EXISTS audits_created_at_idx ON audits(created_at);

CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = CURRENT_TIMESTAMP;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS users_set_updated_at ON users;
CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS calificaciones_set_updated_at ON calificaciones;
CREATE TRIGGER calificaciones_set_updated_at
BEFORE UPDATE ON calificaciones
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

DROP TRIGGER IF EXISTS config_set_updated_at ON config;
CREATE TRIGGER config_set_updated_at
BEFORE UPDATE ON config
FOR EACH ROW EXECUTE FUNCTION set_updated_at();

INSERT INTO config (key, value)
VALUES ('publish_status', 'false')
ON CONFLICT (key) DO NOTHING;
