import React from "react";

const countryToCodeMap = {
  "afganistan": "af",
  "albania": "al",
  "alemania": "de",
  "andorra": "ad",
  "angola": "ao",
  "antigua y barbuda": "ag",
  "arabia saudita": "sa",
  "argelia": "dz",
  "argentina": "ar",
  "armenia": "am",
  "australia": "au",
  "austria": "at",
  "azerbaiyan": "az",
  "bahamas": "bs",
  "banglades": "bd",
  "barbados": "bb",
  "barein": "bh",
  "belgica": "be",
  "belice": "bz",
  "benin": "bj",
  "bielorrusia": "by",
  "birmania": "mm",
  "bolivia": "bo",
  "bosnia y herzegovina": "ba",
  "botsuana": "bw",
  "brasil": "br",
  "brunei": "bn",
  "bulgaria": "bg",
  "burkina faso": "bf",
  "burundi": "bi",
  "butan": "bt",
  "cabo verde": "cv",
  "camboya": "kh",
  "camerun": "cm",
  "canada": "ca",
  "catar": "qa",
  "chad": "td",
  "chile": "cl",
  "china": "cn",
  "chipre": "cy",
  "colombia": "co",
  "comoras": "km",
  "congo": "cg",
  "corea del norte": "kp",
  "corea del sur": "kr",
  "costa de marfil": "ci",
  "costa rica": "cr",
  "croacia": "hr",
  "cuba": "cu",
  "dinamarca": "dk",
  "dominica": "dm",
  "ecuador": "ec",
  "egipto": "eg",
  "el salvador": "sv",
  "emiratos arabes unidos": "ae",
  "eritrea": "er",
  "eslovaquia": "sk",
  "eslovenia": "si",
  "espana": "es",
  "estados unidos": "us",
  "estados unidos de america": "us",
  "eeuu": "us",
  "ee uu": "us",
  "estonia": "ee",
  "esuatini": "sz",
  "etiopia": "et",
  "filipinas": "ph",
  "finlandia": "fi",
  "fiyi": "fj",
  "francia": "fr",
  "gabon": "ga",
  "gambia": "gm",
  "georgia": "ge",
  "ghana": "gh",
  "granada": "gd",
  "grecia": "gr",
  "guatemala": "gt",
  "guinea": "gn",
  "guinea bisau": "gw",
  "guinea ecuatorial": "gq",
  "guyana": "gy",
  "haiti": "ht",
  "honduras": "hn",
  "hungria": "hu",
  "india": "in",
  "indonesia": "id",
  "irak": "iq",
  "iran": "ir",
  "irlanda": "ie",
  "islandia": "is",
  "islas marshall": "mh",
  "islas salomon": "sb",
  "israel": "il",
  "italia": "it",
  "jamaica": "jm",
  "japon": "jp",
  "jordania": "jo",
  "kazajistan": "kz",
  "kenia": "ke",
  "kirguistan": "kg",
  "kiribati": "ki",
  "kuwait": "kw",
  "laos": "la",
  "lesoto": "ls",
  "letonia": "lv",
  "libano": "lb",
  "liberia": "lr",
  "libia": "ly",
  "liechtenstein": "li",
  "lituania": "lt",
  "luxemburgo": "lu",
  "macedonia del norte": "mk",
  "madagascar": "mg",
  "malasia": "my",
  "malaui": "mw",
  "maldivas": "mv",
  "mali": "ml",
  "malta": "mt",
  "marruecos": "ma",
  "mauricio": "mu",
  "mauritania": "mr",
  "mexico": "mx",
  "micronesia": "fm",
  "moldavia": "md",
  "monaco": "mc",
  "mongolia": "mn",
  "montenegro": "me",
  "mozambique": "mz",
  "namibia": "na",
  "nauru": "nr",
  "nepal": "np",
  "nicaragua": "ni",
  "niger": "ne",
  "nigeria": "ng",
  "noruega": "no",
  "nueva zelanda": "nz",
  "oman": "om",
  "paises bajos": "nl",
  "pakistan": "pk",
  "palaos": "pw",
  "panama": "pa",
  "papua nueva guinea": "pg",
  "paraguay": "py",
  "peru": "pe",
  "polonia": "pl",
  "portugal": "pt",
  "reino unido": "gb",
  "republica centroafricana": "cf",
  "republica checa": "cz",
  "republica democratica del congo": "cd",
  "republica dominicana": "do",
  "dominicana": "do",
  "r dominicana": "do",
  "ruanda": "rw",
  "rumania": "ro",
  "rusia": "ru",
  "samoa": "ws",
  "san cristobal y nieves": "kn",
  "san marino": "sm",
  "san vicente y las granadinas": "vc",
  "santa lucia": "lc",
  "santo tome y principe": "st",
  "senegal": "sn",
  "serbia": "rs",
  "seychelles": "sc",
  "sierra leona": "sl",
  "singapur": "sg",
  "siria": "sy",
  "somalia": "so",
  "sri lanka": "lk",
  "sudafrica": "za",
  "sudan": "sd",
  "sudan del sur": "ss",
  "suecia": "se",
  "suiza": "ch",
  "surinam": "sr",
  "tailandia": "th",
  "tanzania": "tz",
  "tayikistan": "tj",
  "timor oriental": "tl",
  "togo": "tg",
  "tonga": "to",
  "trinidad y tobago": "tt",
  "tunez": "tn",
  "turkmenistan": "tm",
  "turquia": "tr",
  "tuvalu": "tv",
  "ucrania": "ua",
  "uganda": "ug",
  "uruguay": "uy",
  "uzbekistan": "uz",
  "vanuatu": "vu",
  "vaticano": "va",
  "venezuela": "ve",
  "vietnam": "vn",
  "yemen": "ye",
  "yibuti": "dj",
  "zambia": "zm",
  "zimbabue": "zw"
};

export function getFlagCode(countryName) {
  if (!countryName) return null;
  const normalized = countryName
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9\s]/g, "")
    .trim();
  return countryToCodeMap[normalized] || null;
}

export function getFlag(countryName, className = "country-flag") {
  const code = getFlagCode(countryName);
  if (!code) return null;
  return (
    <img
      src={`https://flagcdn.com/w40/${code}.png`}
      alt={countryName}
      title={countryName}
      className={className}
      loading="lazy"
    />
  );
}
